-- Projeto: Faturamento
-- Resumo: Pre-invoices por período | Status de pagamento | Tipo de provedor
-- Agrupando: Name (período), SHP_SRM_PRIVN_PRE_INVOICE_TYPE, INVOICE_IDENTIFIER_STATUS
-- Métricas: qtd_rotas_distintas, qtd_pre_invoice_id_distintos, SHP_SRM_PRIVN_COST_AMT
-- Regras de status:
--   - TAC-CPF com status NULL → 'nao_emite_nfs' (se tiver status real, mantém o original)
--   - sap_status_pago_realizado + sap_status_pagado → consolidados em 'sap_status_pago_realizado'
--   - Sempre os 5 últimos períodos (dinâmico)

WITH TopPeriods AS (
  SELECT DISTINCT JSON_EXTRACT_SCALAR(SHP_SRM_PRIVN_PERIOD, '$.name') AS Name
  FROM WHOWNER.BT_SRM_PRE_INVOICE_ASSIGNED_EVENT_COST_ENTITIES
  WHERE SHP_SRM_PRIVN_EVENT_STATUS = 'PROCESSED'
  ORDER BY Name DESC
  LIMIT 5
),

LatestVersion AS (
  SELECT
    SHP_SRM_PRIVN_TRANSACTION_ID,
    MAX(SHP_SRM_PRIVN_VERSION_ID) AS MaxVersion
  FROM WHOWNER.BT_SRM_PRE_INVOICE_ASSIGNED_EVENT_COST_ENTITIES
  WHERE SHP_SRM_PRIVN_EVENT_STATUS = 'PROCESSED'
  GROUP BY SHP_SRM_PRIVN_TRANSACTION_ID
),

Base AS (
  SELECT
    C.SHP_SRM_PRIVN_TRANSACTION_ID,
    JSON_EXTRACT_SCALAR(C.SHP_SRM_PRIVN_PERIOD, '$.name') AS Name,
    C.SHP_SRM_PRIVN_COST_AMT,
    C.SHP_SRM_PRIVN_PRE_INVOICE_TYPE,
    C.SHP_SRM_PRIVN_PRE_INVOICE_ID,
    C.SHP_SRM_PRIVN_RELATED_PERIOD_ID,
    C.SHP_SRM_PRIVN_PAYLOAD,
    PRV.TYPE AS PROVIDER_TYPE,
    CASE
      WHEN PRV.TYPE = 'TAC-CPF' AND T.INVOICE_IDENTIFIER_STATUS IS NULL THEN 'nao_emite_nfs'
      WHEN T.INVOICE_IDENTIFIER_STATUS IN ('sap_status_pago_realizado', 'sap_status_pagado') THEN 'sap_status_pago_realizado'
      ELSE T.INVOICE_IDENTIFIER_STATUS
    END AS INVOICE_IDENTIFIER_STATUS
  FROM WHOWNER.BT_SRM_PRE_INVOICE_ASSIGNED_EVENT_COST_ENTITIES C
  JOIN LatestVersion LV
    ON C.SHP_SRM_PRIVN_TRANSACTION_ID = LV.SHP_SRM_PRIVN_TRANSACTION_ID
   AND C.SHP_SRM_PRIVN_VERSION_ID = LV.MaxVersion
  JOIN TopPeriods TP
    ON JSON_EXTRACT_SCALAR(C.SHP_SRM_PRIVN_PERIOD, '$.name') = TP.Name
  JOIN WHOWNER.BT_SHP_SRM_PROVIDERS PRV
    ON C.SHP_SRM_PRIVN_PROVIDER_ID = PRV.ID
  LEFT JOIN WHOWNER.BT_SRM_INVOICE_FILE_TRACEABILITY T
    ON CAST(C.SHP_SRM_PRIVN_PRE_INVOICE_ID AS STRING) = T.PREINVOICE_ID
  WHERE C.SHP_SRM_PRIVN_EVENT_STATUS = 'PROCESSED'
    AND PRV.TYPE IN ('TAC-CNPJ', 'TAC-CPF', 'ETC', 'MEI')
),

PayloadKeyVals AS (
  SELECT
    b.SHP_SRM_PRIVN_TRANSACTION_ID,
    MAX(IF(JSON_EXTRACT_SCALAR(p, '$.key') = 'external_route_id', JSON_EXTRACT_SCALAR(p, '$.value'), NULL)) AS external_route_id
  FROM Base b,
       UNNEST(JSON_EXTRACT_ARRAY(b.SHP_SRM_PRIVN_PAYLOAD, '$.payload')) AS p
  GROUP BY b.SHP_SRM_PRIVN_TRANSACTION_ID
)

SELECT
  b.Name,
  b.SHP_SRM_PRIVN_PRE_INVOICE_TYPE,
  b.INVOICE_IDENTIFIER_STATUS,
  COUNT(DISTINCT p.external_route_id)            AS qtd_rotas_distintas,
  COUNT(DISTINCT b.SHP_SRM_PRIVN_PRE_INVOICE_ID) AS qtd_pre_invoice_id_distintos,
  SUM(b.SHP_SRM_PRIVN_COST_AMT)                  AS SHP_SRM_PRIVN_COST_AMT
FROM Base b
LEFT JOIN PayloadKeyVals p
  ON b.SHP_SRM_PRIVN_TRANSACTION_ID = p.SHP_SRM_PRIVN_TRANSACTION_ID
-- FILTRO DE TIPO: substituir o comentário abaixo pelo filtro desejado antes de executar
-- Apenas regular:      WHERE b.SHP_SRM_PRIVN_PRE_INVOICE_TYPE = 'regular'
-- Apenas complementar: WHERE b.SHP_SRM_PRIVN_PRE_INVOICE_TYPE = 'complementar'
-- Ambos:               (sem WHERE aqui)
GROUP BY b.Name, b.SHP_SRM_PRIVN_PRE_INVOICE_TYPE, b.INVOICE_IDENTIFIER_STATUS
ORDER BY b.Name DESC, b.SHP_SRM_PRIVN_PRE_INVOICE_TYPE, b.INVOICE_IDENTIFIER_STATUS;
